### ISSUE TITLE
[10.0] web_widget_slickroom test fail

### ISSUE THREAD

**Issue by simahawk** [OCA/web#980]
v10 build seems green but some recent PRs (https://github.com/OCA/web/pull/971) are failing 
probably because of this: https://travis-ci.org/OCA/web/jobs/392778083#L1407

The error looks suspicious
```bash
` AssertionError: ("TypeError: undefined is not a function (evaluating 'odoo.define_section')\n"
```
something might be broken already before this.

**Comment by simahawk** [comment]
@Yajo @moylop260 any idea?

**Comment by yajo** [comment]
That seems to come from https://github.com/OCA/web/pull/958/files#diff-3fbac492c697f6dead3c4eed68754fc7R4, which is an unmerged PR, so I don't see how could that affect other builds...

Branch 11 seems quite healthy:

![captura de pantalla de 2018-07-16 08-18-32](https://user-images.githubusercontent.com/973709/42746668-dfe01d7a-88d0-11e8-8f9e-e01f41cfb613.png)

BTW, that error means:

- `AssertionError`: A weird way of saying that the phantom js test failed.
- `TypeError: undefined is not a function (evaluating 'odoo.define_section')`: `odoo.define_section` is not a function. That was removed for v11, where the test suite changed. Use `odoo.define` now, and possibly rewrite some thingies in tests.

For that reason, closing. Reopen if needed please. Regards!

**Comment by simahawk** [comment]
@Yajo thanks for reporting. Sorry, I messed up a bit (too tired when I submitted this): module name is "web_widget_slickroom" and I linked a bad PR for v11. :sob: 

Actually this error is appearing on https://github.com/OCA/web/pull/971 which is addressing branch 10.0 (as mentioned in the issue title). 
The [error in detail](https://travis-ci.org/OCA/web/jobs/399595700#L1928) is:
```
phantomjs: error
FAIL
FAIL: test_ui_web (odoo.addons.web_widget_slickroom.tests.test_ui.UICase)
` Test backend tests.
Traceback (most recent call last):
`   File "/home/travis/build/OCA/web/web_widget_slickroom/tests/test_ui.py", line 14, in test_ui_web
`     login="admin",
`   File "/home/travis/OCB-10.0/odoo/tests/common.py", line 445, in phantom_js
`     self.phantom_run(cmd, timeout)
`   File "/home/travis/OCB-10.0/odoo/tests/common.py", line 391, in phantom_run
`     "PhantomJS test completed without reporting success; "
` AssertionError: None is not true : PhantomJS test completed without reporting success; the log may contain errors or hints.
FAILED
Module web_widget_slickroom: 1 failures, 0 errors
At least one test failed when loading the modules.
phantomjs: error
FAIL
FAIL: test_ui_web (odoo.addons.web_widget_slick.tests.test_ui.UICase)
` Test backend tests.
Traceback (most recent call last):
`   File "/home/travis/build/OCA/web/web_widget_slick/tests/test_ui.py", line 18, in test_ui_web
`     login="admin",
`   File "/home/travis/OCB-10.0/odoo/tests/common.py", line 445, in phantom_js
`     self.phantom_run(cmd, timeout)
`   File "/home/travis/OCB-10.0/odoo/tests/common.py", line 391, in phantom_run
`     "PhantomJS test completed without reporting success; "
` AssertionError: None is not true : PhantomJS test completed without reporting success; the log may contain errors or hints.
FAILED
Module web_widget_slick: 1 failures, 0 errors
```
And as you see this mention also "web_widget_slick". 
Also, the error traceback sucks like:
```
2018-07-03 14:14:54,050 4376 ERROR openerp_test odoo.addons.web_widget_slickroom.tests.test_ui: ` AssertionError: None is not true : PhantomJS test completed without reporting success; the log may contain errors or hints.
```
making impossible to catch where the error happens (unless I'm deadly blind :smile: )

I'm not working on v10 ATM but if I have a pointer I could check sooner or later :)
/cc @hughesbm (I see your face on test file history :wink: )

**Comment by simahawk** [comment]
FTR: was ES6 syntax on the mentioned PR, not at all related w/ the module reported in the logs :sob:

**Comment by yajo** [comment]
FTR, PhantomJS sucks. :stuck_out_tongue_winking_eye:
